version: 2
run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - goconst
    - gosec
    - gofmt
    - revive
    - gocritic
    - bodyclose
    - unparam
    - ineffassign
    - typecheck

linters-settings:
  gofmt:
    simplify: true

  revive:
    severity: warning
    confidence: 0.8

  goconst:
    min-len: 3
    min-occurrences: 2

issues:
  exclude-rules:
    - linters:
        - errcheck
      source: ".*defer.*"

  max-issues-per-linter: 50
  max-same-issues: 5

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  path-prefix: "."